version: '3'


services:
  backend:
    tty: true
    build:
      context: ./backend
      target: development
    environment:
      DOCKER: 1
      POSTGRES_USER: database
      POSTGRES_PASS: database
      POSTGRES_HOST: pgbouncer
      POSTGRES_PORT: 6432
      POSTGRES_DB: database
    volumes:
      - ./backend:/app

  nginx:
    build:
      context: ./nginx
      target: development
    links:
      - backend
    ports:
      - 8000:8000

  database:
    image: postgres:11-alpine
    logging:
      driver: none
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 333:80
  #   volumes:
  #     - "./pgadmin-servers.json:/pgadmin4/servers.json:ro"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin

  pgbouncer:
    image: pgbouncer/pgbouncer
    logging:
      driver: none
    # ports:
    #   - 6432:6432
    environment:
      PGBOUNCER_LISTEN_PORT: 6432
      PGBOUNCER_LISTEN_ADDR: pgbouncer
      PGBOUNCER_MAX_CLIENT_CONN: 1000
      PGBOUNCER_DEFAULT_POOL_SIZE: 64
      DATABASES_MAX_DB_CONNECTIONS: 64
      DATABASES_HOST: database
      DATABASES_PORT: 5432
      DATABASES_DBNAME: database
      DATABASES_USER: database
      DATABASES_PASSWORD: database
